<a href="https://colab.research.google.com/github/iwacooy/pengembangan-machine-learning/blob/main/klasifikasi_dua_kelas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [4]:
X = np.array([-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
Y = np.array([5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0], dtype=float)

In [5]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1])
    ])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [7]:
model.fit(X, Y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 566ms/step - loss: 97.9936
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 88.4480
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 81.0763
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 75.2309
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 70.4649
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 66.4698
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 63.0325
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 60.0052
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 57.2852
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 54.8012
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - loss: 52.5028
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 50.3548
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 48.3319
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 46.4159
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 44.593

In [8]:
model.predict(np.array([4, 5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[12.999624],
       [13.999659]], dtype=float32)

In [9]:
model.predict(np.array([4, 5])).round()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


array([[13.],
       [14.]], dtype=float32)

In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=20, input_shape=[1]),
    tf.keras.layers.Dense(units=15),
    tf.keras.layers.Dense(units=10),
    tf.keras.layers.Dense(units=1)
    ])

In [11]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [12]:
model.fit(X, Y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 409ms/step - loss: 89.6262
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - loss: 84.4026
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 86.2433
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 68.5919
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 42.1796
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 14.1327
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5.7715
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 15.7865
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 66.0420
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 32.8386
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 4.7434
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1.8079
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 3.4831
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 1.5569
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 2.8333
Epoch 16

In [14]:
model.predict(np.array([4, 5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[12.999903],
       [13.999887]], dtype=float32)

============================================

In [33]:
from sklearn import preprocessing
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [25]:
# Opsi 1 (menggunakan dataset lokal)


# Opsi 2 (menggunakan dataset dari google drive)
df = pd.read_csv('https://drive.google.com/uc?id=1XZbZ5Z7MBXYaR3UO1HbQ4ncPi4R3HsyF')
df.head()

name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [23]:
df.head()

name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

In [26]:
label_encoder = preprocessing.LabelEncoder()
df['name'] = label_encoder.fit_transform(df['name'])
print(df)

      name  diameter  weight  red  green  blue
0        1      2.96   86.76  172     85     2
1        1      3.91   88.05  166     78     3
2        1      4.42   95.17  156     81     2
3        1      4.47   95.60  163     81     4
4        1      4.48   95.76  161     72     9
...    ...       ...     ...  ...    ...   ...
9995     0     15.35  253.89  149     77    20
9996     0     15.41  254.67  148     68     7
9997     0     15.59  256.50  168     82    20
9998     0     15.92  260.14  142     72    11
9999     0     16.45  261.51  152     74     2

[10000 rows x 6 columns]


In [27]:
dataset = df.values

In [29]:
X = dataset[:,1:6]
y = dataset[:,0]

In [30]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [34]:
model = Sequential([
                    Dense(32, activation='relu', input_shape=(5,)),
                    Dense(32, activation='relu'),
                    Dense(1, activation='sigmoid')])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [35]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [36]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5121 - loss: 0.7094
Epoch 2/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8444 - loss: 0.6659
Epoch 3/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8885 - loss: 0.6191
Epoch 4/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9124 - loss: 0.5479
Epoch 5/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9179 - loss: 0.4559
Epoch 6/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9223 - loss: 0.3621
Epoch 7/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9223 - loss: 0.2926
Epoch 8/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9199 - loss: 0.2552
Epoch 9/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9216 - loss: 0.2272
Epoch 10/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9275 - loss: 0.2075
Epoch 11/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9265 - loss: 0.1964
Epoch 12/100
219/219 ━━━━━━━━━━━━━━━━━━━━

In [37]:
model.evaluate(X_test, Y_test, batch_size=1)

3000/3000 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9305 - loss: 0.1737


[0.1746845841407776, 0.9309999942779541]